config/routes.rb
# == Route Map
#
#                     Prefix Verb   URI Pattern                                                                              Controller#Action
#               transactions POST   /transactions(.:format)                                                                  transactions#create
#            new_transaction GET    /transactions/new(.:format)                                                              transactions#new
#                transaction GET    /transactions/:id(.:format)                                                              transactions#show
# connected_accounts_refresh GET    /connected_accounts/refresh(.:format)                                                    connected_accounts#refresh
#     connected_accounts_add GET    /connected_accounts/add(.:format)                                                        connected_accounts#add
#         connected_accounts GET    /connected_accounts(.:format)                                                            connected_accounts#index
#                            POST   /connected_accounts(.:format)                                                            connected_accounts#create
#     edit_connected_account GET    /connected_accounts/:id/edit(.:format)                                                   connected_accounts#edit
#          connected_account PATCH  /connected_accounts/:id(.:format)                                                        connected_accounts#update
#                            PUT    /connected_accounts/:id(.:format)                                                        connected_accounts#update
#                            DELETE /connected_accounts/:id(.:format)                                                        connected_accounts#destroy
#           new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#               user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#       destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#          new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#         edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#              user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                            PUT    /users/password(.:format)                                                                devise/passwords#update
#                            POST   /users/password(.:format)                                                                devise/passwords#create
#   cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#      new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#     edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#          user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                            PUT    /users(.:format)                                                                         devise/registrations#update
#                            DELETE /users(.:format)                                                                         devise/registrations#destroy
#                            POST   /users(.:format)                                                                         devise/registrations#create
#               stripe_event        /stripe_webhooks                                                                         StripeEvent::Engine
#                       root GET    /                                                                                        connected_accounts#index
#         rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#  rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#         rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#  update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#       rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
# 
# Routes for StripeEvent::Engine:
#   root POST /           stripe_event/webhook#event

Rails.application.routes.draw do
  resources :transactions, except: [:edit, :index, :destroy, :update]
  # post 'transactions/stripe_webhooks'
  get 'connected_accounts/refresh'
  get 'connected_accounts/add'
  resources :connected_accounts, except: [:show, :new]
  devise_for :users

  mount StripeEvent::Engine, at: '/stripe_webhooks'

  root 'connected_accounts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/connected_account.rb
# == Schema Information
#
# Table name: connected_accounts
#
#  id                     :integer          not null, primary key
#  sid                    :string
#  name                   :string
#  status                 :string
#  balance                :decimal(8, 2)
#  connected              :date
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  publishable_key        :string
#  refresh_token          :string
#  access_token           :string
#  city                   :string
#  state                  :string
#  postal_code            :string
#  url                    :string
#  dashboard_display_name :string
#  commission             :decimal(5, 2)
#

class ConnectedAccount < ApplicationRecord
  has_many :transactions, dependent: :destroy
  validates :sid, presence: true

  
end

app/controllers/connected_accounts_controller.rb
require 'stripe'
require 'net/http'
class ConnectedAccountsController < ApplicationController
  before_action :set_connected_account, only: [:show, :edit, :update, :destroy]

  # GET /connected_accounts
  # GET /connected_accounts.json
  def index
    @connected_accounts = ConnectedAccount.all
    # list = list_of_accounts_online
    # @accounts = list_of_accounts_online["data"]
  end

  # GET /connected_accounts/1
  # executing show.js.erb
  def show
  end

  # GET /connected_accounts/1/edit
  # executing edit.js.erb
  def edit
  end

  # PATCH/PUT /connected_accounts/1
  # PATCH/PUT /connected_accounts/1.json
  def update
    @connected_account.update(connected_account_params)
    redirect_to connected_accounts_url, notice: 'Connected account was successfully updated.'
    # respond_to do |format|
    #   if @connected_account.update(connected_account_params)
    #     format.html { redirect_to @connected_account, notice: 'Connected account was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @connected_account }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @connected_account.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /connected_accounts/1
  # DELETE /connected_accounts/1.json
  def destroy
    Stripe.api_key = Rails.application.credentials.stripe[Rails.env.to_sym][:secret_key]
    acct = Stripe::Account.retrieve(@connected_account.sid)
    acct.deauthorize(Rails.application.credentials.stripe[Rails.env.to_sym][:client_id])
    @connected_account.destroy
    redirect_to connected_accounts_url, notice: 'Connected account was successfully removed.'
  end

  # GET /connected_accounts/refresh
  def refresh
    # sync local accounts with online stripe accounts
    
    # accounts on stripe
    online_accounts = list_of_accounts_online["data"]
    puts online_accounts

    # update local db based on accounts on stripe

    # added accounts from stripe to local db
    online_accounts.each { |online_account|
      connected_account = ConnectedAccount.where(sid: online_account.id).limit(1)[0]
      if (connected_account.nil?)
        # if account is not in the db, create a new one
        connected_account = ConnectedAccount.new
        connected_account.sid = online_account["id"]
        connected_account.commission = 50
        puts "Found new account online"
        # connected_account.connected = Date.today
      end
      connected_account.name = online_account["business_profile"]["name"]
      # connected_account.status = 
      # connected_account.balance =
      if (online_account["business_profile"]["support_address"])
        connected_account.city = online_account["business_profile"]["support_address"]["city"]
        connected_account.state = online_account["business_profile"]["support_address"]["state"]
        connected_account.postal_code = online_account["business_profile"]["support_address"]["postal_code"]
      end
      connected_account.url = online_account["business_profile"]["url"]
      connected_account.dashboard_display_name = online_account["settings"]["dashboard"]["display_name"]
      puts connected_account.inspect
      connected_account.save
      puts connected_account.errors.inspect
    }

    # removing local accounts that are not there on stripe
    # accounts on db
    connected_accounts = ConnectedAccount.all
    connected_accounts.each { |connected_account| 
      found = false;
      # find connected_account online
      online_accounts.each { |online_account|
        if (connected_account.sid == online_account["id"])
          found = true
        end
      }
      if (found == false)
        connected_account.destroy
      end
    }

    redirect_to connected_accounts_url
  end

  # GET /connected_accounts/add
  def add
    if (stripe_params[:error])
      redirect_to connected_accounts_url, flash: { error: stripe_params[:error_description]} 
      return
    else
      # There is no error.
      # https://stripe.com/docs/connect/standard-accounts#token-request
      
      # Step 4: Fetch the user's credentials from Stripe

      uri = URI('https://connect.stripe.com/oauth/token')
      res = Net::HTTP.post_form(uri, 
        'client_secret' => Rails.application.credentials.stripe[Rails.env.to_sym][:secret_key], 
        'code' => stripe_params[:code], 
        'grant_type' => 'authorization_code')

      @result = JSON.parse(res.body)
      # logger.info "Result from Stripe:"
      # logger.info @result
      if (@result.nil?)
        redirect_to connected_accounts_url, flash: { error: "No response from Stripe"} 
        return
      elsif (@result["error"])
        redirect_to connected_accounts_url, flash: { error: @result["error"] + ": " + @result["error_description"] }
        return
      elsif (@result["stripe_user_id"].nil?)
        redirect_to connected_accounts_url, flash: { error: "stripe_user_id is blank. Cannot proceed. Account was not added." }
        return
      end

      # https://stripe.com/docs/connect/oauth-reference#post-token-response
      # store response in database

      # Searching and Finding: http://www.xyzpub.com/en/ruby-on-rails/4.0/queries.html
      connected_account = ConnectedAccount.where(sid: @result["stripe_user_id"]).limit(1)[0]
      if connected_account.nil?
        connected_account = ConnectedAccount.new
        connected_account.commission = 50
      end
      connected_account.sid = @result["stripe_user_id"]
      connected_account.publishable_key = @result["stripe_publishable_key"]
      connected_account.refresh_token = @result["refresh_token"]
      connected_account.access_token = @result["access_token"]
      connected_account.connected = Date.today

      Stripe.api_key = Rails.application.credentials.stripe[Rails.env.to_sym][:secret_key]
      retrieved_account = Stripe::Account.retrieve(@result["stripe_user_id"])
      # logger.info "Result from Stripe:"
      # logger.info retrieved_account
      
      connected_account.name = retrieved_account["business_profile"]["name"]
      # connected_account.name = retrieved_account["settings"]["dashboard"]["display_name"]
      # connected_account.status = 
      # connected_account.balance =
      if (retrieved_account["business_profile"]["support_address"])
        connected_account.city = retrieved_account["business_profile"]["support_address"]["city"]
        connected_account.state = retrieved_account["business_profile"]["support_address"]["state"]
        connected_account.postal_code = retrieved_account["business_profile"]["support_address"]["postal_code"]
      end
      connected_account.url = retrieved_account["business_profile"]["url"]
      connected_account.dashboard_display_name = retrieved_account["settings"]["dashboard"]["display_name"]

      if connected_account.save
        redirect_to connected_accounts_url, flash: { success: "Stripe Account " + connected_account.dashboard_display_name + " added."} 
      else
        redirect_to connected_accounts_url, flash: { error: connected_account.errors } 
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_connected_account
      @connected_account = ConnectedAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def connected_account_params
      params.require(:connected_account).permit(:commission)
    end

    def stripe_params
      params.permit(:scope, :code, :error, :error_description)
    end

    # Retrieving all connected accounts
    # https://stripe.com/docs/api/accounts/list?lang=curl
    def list_of_accounts_online
      Stripe.api_key = Rails.application.credentials.stripe[Rails.env.to_sym][:secret_key]
      return Stripe::Account.list
    end
end

app/helpers/connected_accounts_helper.rb
module ConnectedAccountsHelper
end

app/views/connected_accounts/_connected_account.erb
<%= content_tag_for(:tr, connected_account) do %>
  <td class="serial-number"><%= serial %></td>
  <td class="account-details-c">
    <div class="name">
      <%= connected_account.dashboard_display_name %> <%= connected_account.name %>
    </div>
    <div class="account-details font-weight-bold">
      <div class="percent">Commission: <%= connected_account.commission %>%</div>
    </div>
    <div class="account-details">
      <div class="business-url">
        <a href="http://<%= connected_account.url %>"><%= connected_account.url %></a>
      </div>

    </div>
    <div class="account-details small">
      <div class="tokens">
        <div class="account-id">ID: <%= connected_account.sid %></div>
        <div class="publishable-key">Public Key: <%= connected_account.publishable_key %> </div>
        <div class="refresh-token">Refresh Token: Hidden </div>
        <div class="access-token">Access Token: Hidden </div>
      </div>
    </div>
  </td>
  <td>
    <ul class="client-actions">
      <li><%= link_to 'Edit', edit_connected_account_path(connected_account), remote: true %> </li>
      <li><%= link_to 'Remove', connected_account, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    </ul>
  </td>

<% end %>

app/views/connected_accounts/_form.html.erb
<%= form_for(connected_account, remote: true) do |form| %>
  <% if connected_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(connected_account.errors.count, "error") %> prohibited this connected_account from being saved:</h2>

      <ul>
      <% connected_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :commission, "New Commission" %>
    <%= form.number_field :commission, {in: 0..100,  class: "form-control"} %>
  </div>
  <div class="actions">
    <%= link_to "Cancel", connected_account, class: "btn btn-secondary btn-sm", remote: true %>
    <%= form.submit "Save Changes", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/connected_accounts/edit.js.erb
$(".alert").remove();
$('#<%= dom_id(@connected_account) %> .tokens').parents().removeClass("small")
$('#<%= dom_id(@connected_account) %> .tokens').parent().append('<%= j(render(partial: "form", locals:{connected_account: @connected_account})) %>');
$('#<%= dom_id(@connected_account) %> .tokens').hide();

app/views/connected_accounts/index.html.erb
<main>
  <section id="client-list">
    <div class="container">`
      <div class="row">
        <div class="col-lg-8 offset-lg-2">
          <% flash.each do |name, msg| %>
            <div class="alert <%= bootstrap_class_for(name) %> alert-dismissible fade show" role="alert">
              <%= msg %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <% end %>
          <div class="p-1"></div>
          <p>In order to add a sub account, click on the button below:</p>
          <a class="btn btn-primary" href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=<%= Rails.application.credentials.stripe[Rails.env.to_sym][:client_id] %>&scope=read_write" role="button"><i class="fab fa-stripe-s"></i> Connect with Stripe</a>
        </div>
      </div>
    </div>
    <div class="clients">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 offset-lg-2">
            <h3>CLIENT LIST</h3>
            <%= link_to "Refresh", connected_accounts_refresh_path, class: "btn btn-primary mt-2" %>
            <%= link_to "New Transaction", new_transaction_path, class: "btn btn-primary mt-2 ml-2" %>
            <table class="accounts-list bg">
              <thead>
                <tr>
                  <th></th>
                  <th>Details</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% serial = 0 %>
                <% @connected_accounts.each do |connected_account| %>
                  <%= render connected_account, serial: serial = serial + 1 %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/connected_accounts/show.js.erb
$(".alert").remove();
var $f = $('#edit_<%= dom_id(@connected_account) %>');
$f.parent().addClass("small");
$f.siblings().show();
$f.remove();