config/routes.rb
# == Route Map
#
#                     Prefix Verb   URI Pattern                                                                              Controller#Action
#               transactions POST   /transactions(.:format)                                                                  transactions#create
#            new_transaction GET    /transactions/new(.:format)                                                              transactions#new
#                transaction GET    /transactions/:id(.:format)                                                              transactions#show
# connected_accounts_refresh GET    /connected_accounts/refresh(.:format)                                                    connected_accounts#refresh
#     connected_accounts_add GET    /connected_accounts/add(.:format)                                                        connected_accounts#add
#         connected_accounts GET    /connected_accounts(.:format)                                                            connected_accounts#index
#                            POST   /connected_accounts(.:format)                                                            connected_accounts#create
#     edit_connected_account GET    /connected_accounts/:id/edit(.:format)                                                   connected_accounts#edit
#          connected_account PATCH  /connected_accounts/:id(.:format)                                                        connected_accounts#update
#                            PUT    /connected_accounts/:id(.:format)                                                        connected_accounts#update
#                            DELETE /connected_accounts/:id(.:format)                                                        connected_accounts#destroy
#           new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#               user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#       destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#          new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#         edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#              user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                            PUT    /users/password(.:format)                                                                devise/passwords#update
#                            POST   /users/password(.:format)                                                                devise/passwords#create
#   cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#      new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#     edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#          user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                            PUT    /users(.:format)                                                                         devise/registrations#update
#                            DELETE /users(.:format)                                                                         devise/registrations#destroy
#                            POST   /users(.:format)                                                                         devise/registrations#create
#               stripe_event        /stripe_webhooks                                                                         StripeEvent::Engine
#                       root GET    /                                                                                        connected_accounts#index
#         rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#  rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#         rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#  update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#       rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
# 
# Routes for StripeEvent::Engine:
#   root POST /           stripe_event/webhook#event

Rails.application.routes.draw do
  resources :transactions, except: [:edit, :index, :destroy, :update]
  # post 'transactions/stripe_webhooks'
  get 'connected_accounts/refresh'
  get 'connected_accounts/add'
  resources :connected_accounts, except: [:show, :new]
  devise_for :users

  mount StripeEvent::Engine, at: '/stripe_webhooks'

  root 'connected_accounts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maximum Floats Dashboard - <%= content_for?(:title) ? yield(:title) : 'List of Accounts' %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark">
        <%= link_to root_path, class: "navbar-brand" do %>
          <i class="fas fa-rocket"></i>
          Maximum Floats Dashboard
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main" aria-controls="navbar-main" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar-main">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if current_page?(connected_accounts_path) || current_page?(root_path) %>">
              <%= link_to "Client List", connected_accounts_path, class: "nav-link" %>
              <!-- <a class="nav-link" href="#">Client List</a> -->
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=<%= Rails.application.credentials.stripe[Rails.env.to_sym][:client_id] %>&scope=read_write">Add Account</a>
            </li>
            <li class="nav-item <%= 'active' if current_page?(new_transaction_path) %>">
              <%= link_to "New Transaction", new_transaction_path, class: "nav-link" %>
            </li>
          </ul>
          <div class="my-2 my-lg-0">
            <button class="btn btn btn-outline-light my-2 my-sm-0" type="submit">Register</button>
            <button class="btn btn btn-outline-light my-2 my-sm-0" type="submit">Log In</button>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer id="site-footer">  
    </footer>
  </body>
</html>